-- Insert sample events to demonstrate the Event Management System with RSVP
INSERT INTO public.events (
  title, description, event_date, end_date, location, max_capacity, 
  registration_required, registration_deadline, cost, category, 
  status, organizer_id, image_url
) VALUES 
  (
    'Sunday Morning Worship Service',
    'Join us for our weekly worship service featuring contemporary music, inspiring messages, and fellowship. All are welcome to experience God''s love in our community.',
    (CURRENT_DATE + INTERVAL '3 days')::timestamp + INTERVAL '10 hours',
    (CURRENT_DATE + INTERVAL '3 days')::timestamp + INTERVAL '11 hours 30 minutes',
    'Main Sanctuary',
    250,
    false,
    null,
    0,
    'worship',
    'published',
    null,
    null
  ),
  (
    'Youth Game Night',
    'An evening of fun games, pizza, and fellowship for our youth group. Bring your friends and join us for an unforgettable night of laughter and community building.',
    (CURRENT_DATE + INTERVAL '5 days')::timestamp + INTERVAL '19 hours',
    (CURRENT_DATE + INTERVAL '5 days')::timestamp + INTERVAL '21 hours',
    'Youth Center',
    30,
    true,
    (CURRENT_DATE + INTERVAL '4 days')::timestamp,
    0,
    'youth',
    'published',
    null,
    null
  ),
  (
    'Marriage Enrichment Workshop',
    'A powerful workshop for couples designed to strengthen marriages through biblical principles, communication skills, and practical tools for lasting relationships.',
    (CURRENT_DATE + INTERVAL '8 days')::timestamp + INTERVAL '18 hours',
    (CURRENT_DATE + INTERVAL '8 days')::timestamp + INTERVAL '21 hours',
    'Conference Room A & B',
    20,
    true,
    (CURRENT_DATE + INTERVAL '6 days')::timestamp,
    2500,
    'family',
    'published',
    null,
    null
  ),
  (
    'Community Food Drive',
    'Help us serve our local community by volunteering for our monthly food drive. We''ll be collecting and distributing food to families in need.',
    (CURRENT_DATE + INTERVAL '10 days')::timestamp + INTERVAL '9 hours',
    (CURRENT_DATE + INTERVAL '10 days')::timestamp + INTERVAL '12 hours',
    'Church Parking Lot',
    50,
    true,
    (CURRENT_DATE + INTERVAL '8 days')::timestamp,
    0,
    'outreach',
    'published',
    null,
    null
  ),
  (
    'Women''s Bible Study Retreat',
    'A weekend retreat for women focused on spiritual growth, sisterhood, and deep study of God''s Word. Includes meals, accommodation, and all materials.',
    (CURRENT_DATE + INTERVAL '15 days')::timestamp + INTERVAL '17 hours',
    (CURRENT_DATE + INTERVAL '17 days')::timestamp + INTERVAL '12 hours',
    'Mountain View Retreat Center',
    40,
    true,
    (CURRENT_DATE + INTERVAL '10 days')::timestamp,
    15000,
    'retreat',
    'published',
    null,
    null
  ),
  (
    'Men''s Prayer Breakfast',
    'Start your Saturday with fellowship, prayer, and encouragement alongside other men in our community. Breakfast will be provided.',
    (CURRENT_DATE + INTERVAL '12 days')::timestamp + INTERVAL '8 hours',
    (CURRENT_DATE + INTERVAL '12 days')::timestamp + INTERVAL '10 hours',
    'Fellowship Hall',
    35,
    true,
    (CURRENT_DATE + INTERVAL '10 days')::timestamp,
    0,
    'fellowship',
    'published',
    null,
    null
  ),
  (
    'Christmas Choir Concert',
    'Join us for a beautiful evening of Christmas music performed by our church choir and special guests. Free admission with optional donations.',
    (CURRENT_DATE + INTERVAL '20 days')::timestamp + INTERVAL '19 hours',
    (CURRENT_DATE + INTERVAL '20 days')::timestamp + INTERVAL '21 hours',
    'Main Sanctuary',
    300,
    true,
    (CURRENT_DATE + INTERVAL '18 days')::timestamp,
    0,
    'music',
    'published',
    null,
    null
  ),
  (
    'Teen Leadership Conference',
    'Empower the next generation! A full-day conference for teens focused on developing leadership skills, faith, and purpose. Lunch included.',
    (CURRENT_DATE + INTERVAL '14 days')::timestamp + INTERVAL '9 hours',
    (CURRENT_DATE + INTERVAL '14 days')::timestamp + INTERVAL '16 hours',
    'Student Center',
    60,
    true,
    (CURRENT_DATE + INTERVAL '12 days')::timestamp,
    1500,
    'youth',
    'published',
    null,
    null
  ),
  (
    'Senior Citizens Fellowship Lunch',
    'A special lunch and fellowship time for our senior members. Enjoy a delicious meal, games, and great company with your church family.',
    (CURRENT_DATE + INTERVAL '7 days')::timestamp + INTERVAL '12 hours',
    (CURRENT_DATE + INTERVAL '7 days')::timestamp + INTERVAL '14 hours',
    'Senior Center Dining Room',
    45,
    true,
    (CURRENT_DATE + INTERVAL '5 days')::timestamp,
    500,
    'fellowship',
    'published',
    null,
    null
  ),
  (
    'New Member Orientation',
    'Welcome to our church family! This orientation helps new members understand our mission, values, and opportunities to get involved in ministry.',
    (CURRENT_DATE + INTERVAL '6 days')::timestamp + INTERVAL '14 hours',
    (CURRENT_DATE + INTERVAL '6 days')::timestamp + INTERVAL '16 hours',
    'Welcome Center',
    25,
    true,
    (CURRENT_DATE + INTERVAL '4 days')::timestamp,
    0,
    'general',
    'published',
    null,
    null
  );