-- Insert sample volunteer opportunities to demonstrate the Volunteer Management System
INSERT INTO public.volunteer_opportunities (
  title, description, department, skills_needed, time_commitment, 
  schedule_type, location, start_date, end_date, max_volunteers, 
  is_urgent, application_deadline, requirements, status, coordinator_id
) VALUES 
  (
    'Sunday Morning Greeter',
    'Welcome church members and visitors with a warm smile and helpful information. Be the first friendly face people see when they arrive for worship.',
    'hospitality',
    ARRAY['Communication', 'Customer Service', 'Friendliness'],
    '1.5 hours per week',
    'weekly',
    'Main Entrance & Welcome Center',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '6 months',
    8,
    false,
    CURRENT_DATE + INTERVAL '2 weeks',
    'Must be available for Sunday morning services. Friendly and outgoing personality required.',
    'active',
    null
  ),
  (
    'Children''s Ministry Assistant',
    'Help create a fun and safe environment for children during Sunday services. Assist with activities, crafts, and maintaining classroom order.',
    'children',
    ARRAY['Working with Children', 'Creativity', 'Patience', 'Organization'],
    '2 hours per week',
    'weekly',
    'Children''s Classrooms',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '1 year',
    6,
    true,
    CURRENT_DATE + INTERVAL '1 week',
    'Background check required. Experience with children preferred. Must be available for Sunday morning services.',
    'active',
    null
  ),
  (
    'Youth Group Leader',
    'Mentor and guide teenagers in their faith journey. Lead discussions, organize activities, and provide support during weekly youth meetings.',
    'youth',
    ARRAY['Leadership', 'Mentoring', 'Communication', 'Event Planning'],
    '3 hours per week',
    'weekly',
    'Youth Center',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '1 year',
    4,
    true,
    CURRENT_DATE + INTERVAL '10 days',
    'Background check required. Experience with teenagers preferred. Must be able to commit to weekly meetings.',
    'active',
    null
  ),
  (
    'Worship Team Musician',
    'Join our worship team to lead the congregation in praise through music. Play instruments or provide vocal support during services.',
    'worship',
    ARRAY['Musical Ability', 'Teamwork', 'Reliability', 'Worship Leadership'],
    '4 hours per week (including practice)',
    'weekly',
    'Main Sanctuary',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '6 months',
    10,
    false,
    CURRENT_DATE + INTERVAL '3 weeks',
    'Musical ability required (voice or instrument). Ability to play by ear or read music. Regular attendance at practice sessions mandatory.',
    'active',
    null
  ),
  (
    'Community Food Drive Coordinator',
    'Organize and oversee monthly food drives for local families in need. Coordinate donations, volunteers, and distribution logistics.',
    'outreach',
    ARRAY['Organization', 'Leadership', 'Communication', 'Project Management'],
    '6 hours per month',
    'monthly',
    'Church Parking Lot & Storage',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '1 year',
    3,
    false,
    CURRENT_DATE + INTERVAL '2 weeks',
    'Strong organizational skills required. Previous volunteer coordination experience preferred.',
    'active',
    null
  ),
  (
    'Audio/Visual Technician',
    'Operate sound and video equipment during services and events. Ensure high-quality audio/visual experience for all attendees.',
    'media',
    ARRAY['Technical Skills', 'Audio/Visual Equipment', 'Problem Solving', 'Attention to Detail'],
    '2 hours per week',
    'weekly',
    'Audio/Visual Booth',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '6 months',
    5,
    true,
    CURRENT_DATE + INTERVAL '1 week',
    'Basic technical aptitude required. Training will be provided. Must be available for Sunday services.',
    'active',
    null
  ),
  (
    'Senior Ministry Volunteer',
    'Assist with senior citizen programs including transportation, meal preparation, and companionship visits.',
    'outreach',
    ARRAY['Compassion', 'Patience', 'Driving', 'Communication'],
    '4 hours per month',
    'flexible',
    'Various Locations',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '1 year',
    12,
    false,
    CURRENT_DATE + INTERVAL '3 weeks',
    'Valid driver''s license required. Background check required. Heart for serving seniors.',
    'active',
    null
  ),
  (
    'Church Office Assistant',
    'Provide administrative support including answering phones, data entry, filing, and assisting with mailings.',
    'admin',
    ARRAY['Office Skills', 'Computer Literacy', 'Organization', 'Communication'],
    '3 hours per week',
    'flexible',
    'Church Office',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '6 months',
    4,
    false,
    CURRENT_DATE + INTERVAL '2 weeks',
    'Basic computer skills required. Previous office experience preferred.',
    'active',
    null
  ),
  (
    'Special Events Setup Crew',
    'Help set up and tear down for special church events, conferences, and celebrations. Physical work involving tables, chairs, and decorations.',
    'hospitality',
    ARRAY['Physical Ability', 'Teamwork', 'Flexibility', 'Reliability'],
    '4 hours per event',
    'one_time',
    'Fellowship Hall & Sanctuary',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '3 months',
    15,
    false,
    CURRENT_DATE + INTERVAL '1 month',
    'Ability to lift 50+ lbs. Flexible schedule for weekend and evening events.',
    'active',
    null
  ),
  (
    'Prayer Ministry Team Member',
    'Provide prayer support for church members and the community. Participate in prayer chains and prayer meetings.',
    'worship',
    ARRAY['Prayer', 'Compassion', 'Confidentiality', 'Spiritual Maturity'],
    '2 hours per week',
    'weekly',
    'Prayer Room',
    CURRENT_DATE,
    CURRENT_DATE + INTERVAL '1 year',
    8,
    false,
    CURRENT_DATE + INTERVAL '2 weeks',
    'Strong prayer life and spiritual maturity required. Ability to maintain confidentiality.',
    'active',
    null
  );