-- Insert sample small groups to demonstrate the Small Group Finder functionality
INSERT INTO public.small_groups (
  name, description, category, meeting_day, meeting_time, location, 
  age_group, gender_preference, max_capacity, is_open_enrollment, 
  status, leader_id, co_leader_id, requirements, image_url
) VALUES 
  (
    'Young Adults Bible Study',
    'A dynamic group exploring God''s Word together through engaging discussions and practical applications for young professionals.',
    'bible_study',
    'Wednesday',
    '7:00 PM',
    'Fellowship Hall - Room B',
    'young_adults',
    'any',
    15,
    true,
    'active',
    null,
    null,
    'Bring your own Bible and notebook. Childcare not provided.',
    null
  ),
  (
    'Men''s Prayer Warriors',
    'Men gathering weekly to pray for our families, church, and community. A time of fellowship and spiritual growth.',
    'prayer',
    'Saturday',
    '6:30 AM',
    'Conference Room A',
    'adults',
    'male',
    12,
    true,
    'active',
    null,
    null,
    'Open to all men 18+. Early morning commitment required.',
    null
  ),
  (
    'Mothers'' Circle',
    'A supportive community for mothers to share experiences, pray together, and study parenting from a biblical perspective.',
    'support',
    'Tuesday',
    '10:00 AM',
    'Children''s Ministry Room',
    'adults',
    'female',
    20,
    true,
    'active',
    null,
    null,
    'Childcare provided. For mothers of children 0-18.',
    null
  ),
  (
    'Youth Discipleship Group',
    'High school students diving deep into faith, leadership, and Christian living through mentorship and peer support.',
    'discipleship',
    'Sunday',
    '4:00 PM',
    'Youth Center',
    'youth',
    'any',
    25,
    true,
    'active',
    null,
    null,
    'Ages 14-18. Parental permission required for under 16.',
    null
  ),
  (
    'Senior Saints Fellowship',
    'A warm community for our senior members to study Scripture, share life experiences, and enjoy meaningful fellowship.',
    'fellowship',
    'Thursday',
    '2:00 PM',
    'Senior Center Lounge',
    'seniors',
    'any',
    30,
    true,
    'active',
    null,
    null,
    'Ages 55+. Transportation assistance available.',
    null
  ),
  (
    'Family Life Group',
    'Families with children learning together about faith, parenting, and building strong Christian households.',
    'fellowship',
    'Sunday',
    '11:30 AM',
    'Family Life Center',
    'families',
    'any',
    40,
    true,
    'active',
    null,
    null,
    'For families with children. Kids activities included.',
    null
  ),
  (
    'Community Service Team',
    'Hands-on ministry serving our local community through food drives, outreach programs, and volunteer projects.',
    'service',
    'Saturday',
    '9:00 AM',
    'Community Outreach Center',
    'adults',
    'any',
    20,
    true,
    'active',
    null,
    null,
    'Physical activity required. Background check needed.',
    null
  ),
  (
    'New Members Integration',
    'A welcoming group helping new church members connect, learn about our community, and find their place to serve.',
    'fellowship',
    'Sunday',
    '12:15 PM',
    'Welcome Center',
    'adults',
    'any',
    15,
    true,
    'active',
    null,
    null,
    'For members who joined within the last 6 months.',
    null
  ),
  (
    'Marriage Enrichment',
    'Couples strengthening their marriages through biblical principles, communication skills, and shared spiritual growth.',
    'support',
    'Friday',
    '7:30 PM',
    'Marriage Ministry Room',
    'adults',
    'any',
    16,
    false,
    'active',
    null,
    null,
    'For married couples only. Couples retreat attendance required.',
    null
  ),
  (
    'College & Career',
    'Young professionals and college students navigating faith in the workplace and academic environments.',
    'discipleship',
    'Wednesday',
    '8:00 PM',
    'Student Center',
    'young_adults',
    'any',
    18,
    true,
    'active',
    null,
    null,
    'Ages 18-28. Mix of students and young professionals.',
    null
  );