-- Insert sample prayer requests to demonstrate the Prayer Request System with Privacy Levels
INSERT INTO public.prayer_requests (
  title, description, category, privacy_level, status, requester_id, 
  requester_name, requester_email, is_anonymous, answered_at, answer_description
) VALUES 
  (
    'Healing for My Grandmother',
    'Please pray for my grandmother who was recently diagnosed with cancer. We are trusting God for healing and peace during this difficult time.',
    'healing',
    'public',
    'ongoing',
    null,
    'Sarah Johnson',
    'sarah.j@email.com',
    false,
    null,
    null
  ),
  (
    'Job Search Guidance',
    'I have been searching for a new job for several months. Please pray for Gods guidance in finding the right opportunity and for favor with potential employers.',
    'guidance',
    'members',
    'open',
    null,
    'Michael Chen',
    'mchen@email.com',
    false,
    null,
    null
  ),
  (
    'Family Reconciliation',
    'There has been tension and conflict in our family for the past year. Please pray for forgiveness, understanding, and restoration of our relationships.',
    'family',
    'members',
    'open',
    null,
    null,
    null,
    true,
    null,
    null
  ),
  (
    'Youth Ministry Growth',
    'Please pray for our youth ministry as we seek to reach more teenagers in our community and help them grow in their faith journey.',
    'ministry',
    'public',
    'ongoing',
    null,
    'Pastor David',
    'pastor.david@church.org',
    false,
    null,
    null
  ),
  (
    'Financial Breakthrough',
    'My family is facing financial difficulties due to unexpected medical bills. Please pray for Gods provision and wisdom in managing our resources.',
    'general',
    'members',
    'open',
    null,
    'Jennifer Martinez',
    'jmartinez@email.com',
    false,
    null,
    null
  ),
  (
    'Safe Travel for Mission Trip',
    'Our mission team is traveling to Guatemala next week. Please pray for safe travels, good health, and effective ministry during our time there.',
    'ministry',
    'public',
    'open',
    null,
    'Mission Team Leader',
    'missions@church.org',
    false,
    null,
    null
  ),
  (
    'Marriage Restoration',
    'Please pray for my marriage. We are going through a very difficult season and considering separation. We need Gods intervention and healing.',
    'family',
    'private',
    'ongoing',
    null,
    null,
    null,
    true,
    null,
    null
  ),
  (
    'College Decision',
    'I am a high school senior trying to decide which college to attend. Please pray for wisdom and clarity as I make this important decision.',
    'guidance',
    'public',
    'open',
    null,
    'Emma Wilson',
    'emma.w@email.com',
    false,
    null,
    null
  ),
  (
    'Church Building Fund',
    'Please pray for our church building project. We are seeking Gods direction and provision for the funds needed to expand our facilities.',
    'ministry',
    'public',
    'ongoing',
    null,
    'Building Committee',
    'building@church.org',
    false,
    null,
    null
  ),
  (
    'Successful Surgery Recovery',
    'Thank you for your prayers! My father surgery went well and he is recovering nicely. God is faithful and we are grateful for His healing hand.',
    'healing',
    'public',
    'answered',
    null,
    'Lisa Thompson',
    'lisa.t@email.com',
    false,
    CURRENT_DATE - INTERVAL '3 days',
    'The surgery was completely successful and dad is healing faster than expected. The doctors are amazed at his progress. Thank you for your faithful prayers!'
  ),
  (
    'New Job Blessing',
    'Praise God! After months of searching, I received a job offer that is perfect for my family situation. Thank you for your prayers and support.',
    'guidance',
    'public',
    'answered',
    null,
    'Robert Kim',
    'robert.kim@email.com',
    false,
    CURRENT_DATE - INTERVAL '1 week',
    'I start my new position next Monday. The salary is more than I hoped for and the schedule allows me to spend more time with my children. God answers prayers!'
  ),
  (
    'Addiction Recovery',
    'Please pray for strength and guidance as I work through addiction recovery. This is a daily battle and I need Gods help and the support of this community.',
    'general',
    'members',
    'ongoing',
    null,
    null,
    null,
    true,
    null,
    null
  );